export type UserSettingsForm = {
    email: string,
    confirmemail: string,
    username: string,
    name: string,
    password: string,
    consfirmpassword: string,
    cardnumber: string,
    cardname: string,
    expirydate: string,
    cvv: string,
    address: string,
    city: string,
    state: string,
    zipcode: string,
    country: string,
  }